import React, { useState } from 'react';
import {
  ArrowLeft,
  UserPlus,
  ArrowRight,
  ShieldCheck,
  AlertCircle,
  CheckCircle2,
  Phone,
  Lock,
  Copy,
  Check,
  Eye,
} from 'lucide-react';
import { PatientProfile } from '../../types';

interface WorkerRegisterPatientProps {
  onBack: () => void;
  onRegisterComplete: (patient: PatientProfile, startScreeningImmediately: boolean) => void;
}

export const WorkerRegisterPatient: React.FC<WorkerRegisterPatientProps> = ({
  onBack,
  onRegisterComplete,
}) => {
  // Generate random new ID e.g. RX104582
  const randomNum = Math.floor(100000 + Math.random() * 900000);
  const autoGeneratedId = `RX${randomNum}`;

  const [fullName, setFullName] = useState('');
  const [age, setAge] = useState<number | ''>(52);
  const [gender, setGender] = useState<'Male' | 'Female' | 'Other'>('Male');
  const [phone, setPhone] = useState('+1 (555) 392-8172');
  const [areaVillage, setAreaVillage] = useState('East Valley Sector 4');
  const [address, setAddress] = useState('House 42, Green Avenue, East Valley');

  // Emergency contact fields
  const [emergencyName, setEmergencyName] = useState('David Vance');
  const [emergencyPhone, setEmergencyPhone] = useState('+1 (555) 912-3482');
  const [emergencyRelation, setEmergencyRelation] = useState('Spouse');

  // Phone / OTP Verification
  const [otpSent, setOtpSent] = useState(false);
  const [otpCode, setOtpCode] = useState('4829');
  const [isOtpVerified, setIsOtpVerified] = useState(true);

  // Clinical info
  const [diabetesType, setDiabetesType] = useState<'Type 1' | 'Type 2' | 'Gestational'>('Type 2');
  const [durationYears, setDurationYears] = useState<number | ''>(7);
  const [medications, setMedications] = useState('Metformin 500mg BID, Glipizide 5mg QD');
  const [notes, setNotes] = useState('Patient reported occasional hazy vision during night reading. No previous retinal laser.');

  const [error, setError] = useState('');
  const [registeredPatient, setRegisteredPatient] = useState<PatientProfile | null>(null);
  const [copied, setCopied] = useState(false);

  const handleSendOtp = () => {
    setOtpSent(true);
    setIsOtpVerified(true);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!fullName.trim()) {
      setError('Please provide the patient full name.');
      return;
    }
    if (!phone.trim()) {
      setError('Please provide the primary mobile number.');
      return;
    }
    if (!areaVillage.trim()) {
      setError('Please provide the area/village name.');
      return;
    }

    const newPatient: PatientProfile = {
      id: autoGeneratedId,
      name: fullName.trim(),
      role: 'Patient',
      age: Number(age) || 50,
      gender,
      phone: phone.trim(),
      area: areaVillage.trim(),
      diabetesType,
      durationYears: Number(durationYears) || 5,
      medications: medications.trim(),
      notes: `${notes.trim()} (Address: ${address}, Emergency: ${emergencyName} - ${emergencyPhone} [${emergencyRelation}])`,
    };

    setRegisteredPatient(newPatient);
  };

  const handleCopyId = () => {
    if (registeredPatient) {
      navigator.clipboard.writeText(registeredPatient.id);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  // SUCCESS SCREEN MATCHING SPEC:
  // "On success: auto-generate ID (e.g. RX104582), "Patient ID created — save it for future screenings,"
  // then Create Screening Session / Go Back."
  if (registeredPatient) {
    return (
      <div className="max-w-2xl mx-auto px-4 sm:px-6 py-12">
        <div className="bg-white rounded-2xl border border-teal-200 p-8 sm:p-10 shadow-lg text-center space-y-6">
          <div className="w-16 h-16 rounded-full bg-teal-50 border-2 border-teal-500 text-teal-700 flex items-center justify-center mx-auto">
            <CheckCircle2 className="w-9 h-9" />
          </div>

          <div className="space-y-2">
            <h2 className="text-2xl font-bold text-gray-950">
              Registration Successful
            </h2>
            <p className="text-sm text-teal-800 font-medium">
              Patient ID created — save it for future screenings.
            </p>
          </div>

          {/* Generated ID Box */}
          <div className="bg-teal-50/60 border border-teal-200 rounded-2xl p-6 max-w-md mx-auto">
            <span className="text-xs uppercase tracking-wider text-teal-800 font-semibold block mb-1">
              Official Patient Identifier
            </span>
            <div className="flex items-center justify-center gap-3">
              <span className="text-3xl font-mono font-bold text-teal-950 tracking-wider">
                {registeredPatient.id}
              </span>
              <button
                onClick={handleCopyId}
                className="p-2 text-teal-700 hover:text-teal-950 hover:bg-teal-100 rounded-lg transition-colors"
                title="Copy Patient ID"
              >
                {copied ? <Check className="w-5 h-5 text-emerald-600" /> : <Copy className="w-5 h-5" />}
              </button>
            </div>
            <p className="text-xs text-gray-500 mt-2">
              Assigned to: <strong>{registeredPatient.name}</strong> • {registeredPatient.age}y {registeredPatient.gender}
            </p>
            <p className="text-xs text-gray-500">
              {registeredPatient.area} • Phone: {registeredPatient.phone}
            </p>
          </div>

          {/* Action Buttons: Create Screening Session / Go Back */}
          <div className="pt-4 flex flex-col sm:flex-row items-center justify-center gap-4">
            <button
              id="worker-create-screening-btn"
              onClick={() => onRegisterComplete(registeredPatient, true)}
              className="w-full sm:w-auto px-6 py-3 bg-teal-800 hover:bg-teal-900 text-white font-bold text-sm rounded-xl transition-all shadow-xs inline-flex items-center justify-center gap-2"
            >
              <Eye className="w-4 h-4" />
              <span>Create Screening Session</span>
            </button>

            <button
              id="worker-register-goback-btn"
              onClick={() => onRegisterComplete(registeredPatient, false)}
              className="w-full sm:w-auto px-6 py-3 bg-white border border-gray-300 hover:bg-gray-50 text-gray-700 font-semibold text-sm rounded-xl transition-colors"
            >
              Go Back
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8">
      {/* Back button */}
      <button
        onClick={onBack}
        className="inline-flex items-center gap-2 text-xs font-semibold text-gray-600 hover:text-teal-800 transition-colors mb-6"
      >
        <ArrowLeft className="w-4 h-4" />
        <span>Back to Field Hub</span>
      </button>

      <div className="bg-white rounded-2xl border border-gray-200 p-6 sm:p-9 shadow-xs">
        <div className="flex items-center gap-3 mb-6 pb-4 border-b border-gray-100">
          <div className="w-12 h-12 rounded-xl bg-teal-50 border border-teal-200 text-teal-700 flex items-center justify-center">
            <UserPlus className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-gray-950">
              New Patient Intake Registration
            </h1>
            <p className="text-xs text-gray-500">
              Enter patient demographics, contact info, emergency verification, and clinical diabetes background.
            </p>
          </div>
        </div>

        {error && (
          <div className="mb-6 p-3.5 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Section 1: Demographics */}
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-teal-800 mb-3">
              1. Basic Demographics
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="sm:col-span-2">
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Full Name *
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Eleanor Vance"
                  value={fullName}
                  onChange={(e) => setFullName(e.target.value)}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500 font-medium"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Gender *
                </label>
                <select
                  value={gender}
                  onChange={(e) => setGender(e.target.value as any)}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500 bg-white"
                >
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                  <option value="Other">Other</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-4">
              <div>
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Age (Years) *
                </label>
                <input
                  type="number"
                  required
                  min={1}
                  max={120}
                  value={age}
                  onChange={(e) => setAge(e.target.value ? Number(e.target.value) : '')}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Area / Village *
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. East Valley Sector 4"
                  value={areaVillage}
                  onChange={(e) => setAreaVillage(e.target.value)}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Residential Address
                </label>
                <input
                  type="text"
                  placeholder="Street / House No."
                  value={address}
                  onChange={(e) => setAddress(e.target.value)}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500"
                />
              </div>
            </div>
          </div>

          {/* Section 2: Contact & Phone/OTP Verification */}
          <div className="pt-4 border-t border-gray-100">
            <h3 className="text-xs font-bold uppercase tracking-wider text-teal-800 mb-3">
              2. Phone & OTP Verification
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 items-end">
              <div className="sm:col-span-2">
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Patient Mobile Phone *
                </label>
                <input
                  type="tel"
                  required
                  placeholder="+1 (555) 000-0000"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500"
                />
              </div>

              <div>
                {isOtpVerified ? (
                  <div className="h-10 px-3 bg-emerald-50 border border-emerald-200 rounded-xl flex items-center justify-center gap-1.5 text-xs font-bold text-emerald-800">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    <span>Phone Verified (OTP)</span>
                  </div>
                ) : (
                  <button
                    type="button"
                    onClick={handleSendOtp}
                    className="w-full h-10 px-3 bg-teal-50 border border-teal-300 hover:bg-teal-100 text-teal-800 text-xs font-bold rounded-xl transition-colors"
                  >
                    {otpSent ? 'Resend OTP' : 'Send & Verify OTP'}
                  </button>
                )}
              </div>
            </div>
          </div>

          {/* Section 3: Emergency Contact */}
          <div className="pt-4 border-t border-gray-100">
            <h3 className="text-xs font-bold uppercase tracking-wider text-teal-800 mb-3">
              3. Emergency Contact Details
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div>
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Emergency Contact Name *
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. David Vance"
                  value={emergencyName}
                  onChange={(e) => setEmergencyName(e.target.value)}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Emergency Contact Phone *
                </label>
                <input
                  type="tel"
                  required
                  placeholder="+1 (555) 912-3482"
                  value={emergencyPhone}
                  onChange={(e) => setEmergencyPhone(e.target.value)}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500"
                />
              </div>

              <div>
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Relationship *
                </label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Spouse / Child / Guardian"
                  value={emergencyRelation}
                  onChange={(e) => setEmergencyRelation(e.target.value)}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500"
                />
              </div>
            </div>
          </div>

          {/* Section 4: Clinical History */}
          <div className="pt-4 border-t border-gray-100">
            <h3 className="text-xs font-bold uppercase tracking-wider text-teal-800 mb-3">
              4. Diabetes History & Medications
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Diabetes Type *
                </label>
                <select
                  value={diabetesType}
                  onChange={(e) => setDiabetesType(e.target.value as any)}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500 bg-white"
                >
                  <option value="Type 2">Type 2 Diabetes Mellitus (T2D)</option>
                  <option value="Type 1">Type 1 Diabetes Mellitus (T1D)</option>
                  <option value="Gestational">Gestational Diabetes</option>
                </select>
              </div>

              <div>
                <label className="block text-xs font-semibold text-gray-700 mb-1">
                  Duration of Diabetes (Years) *
                </label>
                <input
                  type="number"
                  min={0}
                  max={60}
                  value={durationYears}
                  onChange={(e) => setDurationYears(e.target.value ? Number(e.target.value) : '')}
                  className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500"
                />
              </div>
            </div>

            <div className="mt-4">
              <label className="block text-xs font-semibold text-gray-700 mb-1">
                Current Medications & Insulin Regimen
              </label>
              <input
                type="text"
                placeholder="e.g. Metformin 500mg, Lantus Insulin 15 units qhs"
                value={medications}
                onChange={(e) => setMedications(e.target.value)}
                className="w-full text-xs border border-gray-300 rounded-xl px-3 py-2.5 focus:ring-teal-500 focus:border-teal-500"
              />
            </div>

            <div className="mt-4">
              <label className="block text-xs font-semibold text-gray-700 mb-1">
                Clinical Intake Notes & Visual Complaints
              </label>
              <textarea
                rows={3}
                placeholder="Record any ocular symptoms, blurry vision, floaters, or glycemic control history..."
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                className="w-full text-xs border border-gray-300 rounded-xl p-3 focus:ring-teal-500 focus:border-teal-500"
              />
            </div>
          </div>

          <div className="pt-4 border-t border-gray-100 flex flex-col sm:flex-row items-center justify-between gap-4">
            <span className="text-xs text-gray-500">
              * A unique Patient ID will be automatically generated upon submission.
            </span>

            <button
              id="worker-register-submit-btn"
              type="submit"
              className="w-full sm:w-auto px-6 py-2.5 bg-teal-800 hover:bg-teal-900 text-white font-bold text-xs sm:text-sm rounded-xl transition-colors shadow-xs inline-flex items-center justify-center gap-2"
            >
              <span>Complete Registration</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
