import { DoctorUser, WorkerUser, PatientUser, ScreeningSession, ReferralRecord, NotificationItem } from './types';

export const INITIAL_DOCTOR: DoctorUser = {
  id: 'DOC-9041',
  name: 'Dr. Alistair Vance, MD',
  role: 'Doctor',
  email: 'a.vance@eyeinstitute.org',
  phone: '+1 (555) 438-9210',
  hospital: 'St. Jude Eye Institute & Vitreoretinal Center',
  specialization: 'Vitreoretinal Specialist & Ophthalmologist',
  regNumber: 'MD-OPH-78921',
  avatarInitials: 'AV',
  stats: {
    reviewed: 148,
    referred: 32,
    totalSessions: 194,
  },
};

export const INITIAL_WORKER: WorkerUser = {
  id: 'WRK-3082',
  name: 'Maya Chen, CHW',
  role: 'Healthcare Worker',
  email: 'm.chen@fieldhealth.org',
  phone: '+1 (555) 283-7741',
  area: 'East Valley PHC Sector 4',
  organization: 'District Rural Tele-Ophthalmology Program',
  avatarInitials: 'MC',
  stats: {
    patientsRegistered: 86,
    sessionsCompleted: 112,
  },
};

export const INITIAL_PATIENTS: PatientUser[] = [
  {
    id: 'RX-104582',
    name: 'Eleanor Vance',
    role: 'Patient',
    age: 62,
    gender: 'Female',
    phone: '+1 (555) 912-3482',
    area: 'East Valley, Sector 4',
    address: '742 Evergreen Terrace, East Valley',
    emergencyContact: {
      name: 'Thomas Vance',
      relationship: 'Spouse',
      phone: '+1 (555) 912-3485',
    },
    lastScreeningDate: 'Today, 08:30 AM',
    totalScreenings: 4,
    overallStatus: 'High Risk',
  },
  {
    id: 'RX-104583',
    name: 'Marcus Brody',
    role: 'Patient',
    age: 58,
    gender: 'Male',
    phone: '+1 (555) 349-1180',
    area: 'Riverside Rural Unit',
    address: '12 Riverbank Way, Riverside',
    emergencyContact: {
      name: 'Sarah Brody',
      relationship: 'Daughter',
      phone: '+1 (555) 349-1184',
    },
    lastScreeningDate: 'Yesterday, 03:15 PM',
    totalScreenings: 3,
    overallStatus: 'Referable',
  },
  {
    id: 'RX-104584',
    name: 'Sunita Patel',
    role: 'Patient',
    age: 49,
    gender: 'Female',
    phone: '+1 (555) 772-9903',
    area: 'Greenfield Clinic',
    address: '45 Lotus Court, Greenfield',
    emergencyContact: {
      name: 'Raj Patel',
      relationship: 'Brother',
      phone: '+1 (555) 772-9901',
    },
    lastScreeningDate: 'Sep 06, 2026',
    totalScreenings: 2,
    overallStatus: 'Needs Review',
  },
  {
    id: 'RX-104585',
    name: 'David Miller',
    role: 'Patient',
    age: 54,
    gender: 'Male',
    phone: '+1 (555) 881-2234',
    area: 'Oakridge Community Health',
    address: '88 Timberland Rd, Oakridge',
    emergencyContact: {
      name: 'Claire Miller',
      relationship: 'Spouse',
      phone: '+1 (555) 881-2239',
    },
    lastScreeningDate: 'Sep 05, 2026',
    totalScreenings: 5,
    overallStatus: 'Low Risk',
  },
  {
    id: 'RX-104586',
    name: 'Amina Yusuf',
    role: 'Patient',
    age: 67,
    gender: 'Female',
    phone: '+1 (555) 604-3319',
    area: 'East Valley, Sector 2',
    address: '109 Cedar Avenue, East Valley',
    emergencyContact: {
      name: 'Tariq Yusuf',
      relationship: 'Son',
      phone: '+1 (555) 604-3320',
    },
    lastScreeningDate: 'Sep 04, 2026',
    totalScreenings: 1,
    overallStatus: 'Referable',
  },
  {
    id: 'RX-104587',
    name: 'Robert Chen',
    role: 'Patient',
    age: 43,
    gender: 'Male',
    phone: '+1 (555) 412-8877',
    area: 'Metro Outreach Post',
    address: '320 High St, Metro Center',
    emergencyContact: {
      name: 'Lily Chen',
      relationship: 'Sister',
      phone: '+1 (555) 412-8878',
    },
    lastScreeningDate: 'Sep 02, 2026',
    totalScreenings: 2,
    overallStatus: 'Low Risk',
  },
];

export const INITIAL_SESSIONS: ScreeningSession[] = [
  {
    id: 'SESS-2026-0891',
    patientId: 'RX-104582',
    patientName: 'Eleanor Vance',
    patientAge: 62,
    patientGender: 'Female',
    patientArea: 'East Valley, Sector 4',
    date: 'Today, 08:30 AM',
    laterality: 'Right Eye (OD)',
    riskLevel: 'High Risk',
    imageQuality: 'Good',
    drGrade: 'Severe NPDR',
    isReferable: true,
    reviewStatus: 'Pending Review',
    workerId: 'WRK-3082',
    workerName: 'Maya Chen',
    originalImageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    aiReport: {
      iqa: {
        status: 'Good',
        score: 94,
        sharpness: 'High (0.88 Laplacian score)',
        illumination: 'Uniformly calibrated across 45° field',
        fieldOfView: 'Full macula and optic disc centered',
      },
      drClassification: {
        grade: 'Severe NPDR',
        confidence: 96.4,
        icdrScale: 3,
      },
      referableDR: {
        isReferable: true,
        confidence: 98.2,
        criteria: 'Multiple blot hemorrhages in 4 quadrants, prominent venous beading, hard exudate rings.',
      },
      microaneurysms: {
        detected: true,
        count: 24,
        quadrants: ['Superior-Temporal', 'Inferior-Temporal', 'Nasal'],
        details: 'Clusters observed in perifoveal capillary bed, diameter 25-40 microns.',
      },
      hemorrhages: {
        detected: true,
        type: 'Flame-shaped & deep dot-blot hemorrhages',
        quadrants: ['All 4 quadrants (meets 4:2:1 ICDR criteria)'],
        details: 'Intense microvascular breakdown in mid-periphery.',
      },
      exudates: {
        detected: true,
        pattern: 'Hard lipid circinate ring entering within 500 microns of foveal center',
        macularInvolvement: true,
        details: 'Significant macular edema hazard; lipid deposition rings prominent.',
      },
      opticDisc: {
        status: 'Normal',
        cupToDiscRatio: 0.35,
        marginClarity: 'Sharp neural rim margins, no neovascularization at disc (NVD)',
        details: 'Disc appears healthy with normal physiologic pallor.',
      },
      vesselAnalysis: {
        status: 'Abnormal',
        arteriovenousNicking: true,
        tortuosity: 'Marked venous beading and dilatation',
        caliberRatio: 'AV ratio 0.52 (Arteriolar narrowing with venous engorgement)',
        details: 'Generalized microvascular sclerosis and early intraretinal microvascular abnormalities (IRMA).',
      },
    },
  },
  {
    id: 'SESS-2026-0888',
    patientId: 'RX-104583',
    patientName: 'Marcus Brody',
    patientAge: 58,
    patientGender: 'Male',
    patientArea: 'Riverside Rural Unit',
    date: 'Yesterday, 03:15 PM',
    laterality: 'Left Eye (OS)',
    riskLevel: 'Referable',
    imageQuality: 'Good',
    drGrade: 'Moderate NPDR',
    isReferable: true,
    reviewStatus: 'Pending Review',
    workerId: 'WRK-3082',
    workerName: 'Maya Chen',
    originalImageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    aiReport: {
      iqa: {
        status: 'Good',
        score: 91,
        sharpness: 'Good focus on posterior pole',
        illumination: 'Balanced non-mydriatic exposure',
        fieldOfView: '45 degree field well centered',
      },
      drClassification: {
        grade: 'Moderate NPDR',
        confidence: 93.1,
        icdrScale: 2,
      },
      referableDR: {
        isReferable: true,
        confidence: 94.7,
        criteria: 'More than mild microaneurysms and hard exudates close to macula.',
      },
      microaneurysms: {
        detected: true,
        count: 11,
        quadrants: ['Inferior-Temporal', 'Superior-Temporal'],
        details: 'Punctate microaneurysms near macular avascular zone edge.',
      },
      hemorrhages: {
        detected: true,
        type: 'Isolated dot-blot intraretinal lesions',
        quadrants: ['Inferior-Temporal'],
        details: 'Four distinct dot-blot hemorrhages without subhyaloid extension.',
      },
      exudates: {
        detected: true,
        pattern: 'Small clusters of hard exudates',
        macularInvolvement: false,
        details: 'Hard exudates located > 1 disc diameter from foveola.',
      },
      opticDisc: {
        status: 'Normal',
        cupToDiscRatio: 0.32,
        marginClarity: 'Crisp disc margins, normal neuroretinal rim',
        details: 'No swelling or neovascularization.',
      },
      vesselAnalysis: {
        status: 'Normal',
        arteriovenousNicking: false,
        tortuosity: 'Mild venular tortuosity',
        caliberRatio: 'AV ratio 0.65 (within normal limits)',
        details: 'Stable vascular architecture.',
      },
    },
  },
  {
    id: 'SESS-2026-0882',
    patientId: 'RX-104584',
    patientName: 'Sunita Patel',
    patientAge: 49,
    patientGender: 'Female',
    patientArea: 'Greenfield Clinic',
    date: 'Sep 06, 2026',
    laterality: 'Both Eyes (OU)',
    riskLevel: 'Needs Review',
    imageQuality: 'Acceptable',
    drGrade: 'Mild NPDR',
    isReferable: false,
    reviewStatus: 'Pending Review',
    workerId: 'WRK-3082',
    workerName: 'Maya Chen',
    originalImageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    aiReport: {
      iqa: {
        status: 'Acceptable',
        score: 74,
        sharpness: 'Slight motion blur on superior nasal quadrant',
        illumination: 'Mild glare on inferotemporal perimeter',
        fieldOfView: 'Slightly off-center macula',
      },
      drClassification: {
        grade: 'Mild NPDR',
        confidence: 81.2,
        icdrScale: 1,
      },
      referableDR: {
        isReferable: false,
        confidence: 82.0,
        criteria: 'Sparse microaneurysms only, no exudates near fovea.',
      },
      microaneurysms: {
        detected: true,
        count: 3,
        quadrants: ['Temporal'],
        details: 'Isolated faint microaneurysms.',
      },
      hemorrhages: {
        detected: false,
        type: 'None detected',
        quadrants: [],
        details: 'No overt retinal hemorrhages observed.',
      },
      exudates: {
        detected: false,
        pattern: 'None detected',
        macularInvolvement: false,
        details: 'No hard or soft exudates.',
      },
      opticDisc: {
        status: 'Suspect',
        cupToDiscRatio: 0.55,
        marginClarity: 'Superior margin slightly blurred by media haze',
        details: 'Borderline cupping warrants doctor clinical review.',
      },
      vesselAnalysis: {
        status: 'Normal',
        arteriovenousNicking: false,
        tortuosity: 'Normal',
        caliberRatio: 'AV ratio 0.67',
        details: 'Normal vascular branches.',
      },
    },
  },
  {
    id: 'SESS-2026-0879',
    patientId: 'RX-104585',
    patientName: 'David Miller',
    patientAge: 54,
    patientGender: 'Male',
    patientArea: 'Oakridge Community Health',
    date: 'Sep 05, 2026',
    laterality: 'Right Eye (OD)',
    riskLevel: 'Low Risk',
    imageQuality: 'Good',
    drGrade: 'No DR',
    isReferable: false,
    reviewStatus: 'Reviewed',
    workerId: 'WRK-3082',
    workerName: 'Maya Chen',
    originalImageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    doctorAssessment: {
      doctorId: 'DOC-9041',
      doctorName: 'Dr. Alistair Vance, MD',
      decision: 'No immediate referral',
      notes: 'No signs of diabetic retinopathy. Retinal architecture is healthy. Recommend routine 12-month community screening.',
      submittedAt: 'Sep 05, 2026 at 04:20 PM',
    },
    aiReport: {
      iqa: {
        status: 'Good',
        score: 98,
        sharpness: 'Excellent high-definition capture',
        illumination: 'Optimal contrast and field illumination',
        fieldOfView: 'Full standard ETDRS field 1 & 2',
      },
      drClassification: {
        grade: 'No DR',
        confidence: 99.4,
        icdrScale: 0,
      },
      referableDR: {
        isReferable: false,
        confidence: 99.8,
        criteria: 'Clear fundus, zero referable lesion signatures.',
      },
      microaneurysms: {
        detected: false,
        count: 0,
        quadrants: [],
        details: 'Zero microaneurysms detected across entire field.',
      },
      hemorrhages: {
        detected: false,
        type: 'None',
        quadrants: [],
        details: 'Zero hemorrhages detected.',
      },
      exudates: {
        detected: false,
        pattern: 'None',
        macularInvolvement: false,
        details: 'Zero exudates or lipid formations.',
      },
      opticDisc: {
        status: 'Normal',
        cupToDiscRatio: 0.28,
        marginClarity: 'Sharp distinct margins, healthy pink neuroretinal rim',
        details: 'Completely unremarkable physiologic disc.',
      },
      vesselAnalysis: {
        status: 'Normal',
        arteriovenousNicking: false,
        tortuosity: 'Normal arborization',
        caliberRatio: 'AV ratio 0.68',
        details: 'Healthy patent retinal vascular tree.',
      },
    },
  },
  {
    id: 'SESS-2026-0870',
    patientId: 'RX-104586',
    patientName: 'Amina Yusuf',
    patientAge: 67,
    patientGender: 'Female',
    patientArea: 'East Valley, Sector 2',
    date: 'Sep 04, 2026',
    laterality: 'Both Eyes (OU)',
    riskLevel: 'Referable',
    imageQuality: 'Good',
    drGrade: 'Moderate NPDR',
    isReferable: true,
    reviewStatus: 'Referred',
    workerId: 'WRK-3082',
    workerName: 'Maya Chen',
    originalImageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    doctorAssessment: {
      doctorId: 'DOC-9041',
      doctorName: 'Dr. Alistair Vance, MD',
      decision: 'Refer to hospital',
      notes: 'Clinically significant macular edema (CSME) suspected. Prompt OCT scan and evaluation by vitreoretinal specialist needed.',
      hospitalName: 'St. Jude Eye Institute',
      submittedAt: 'Sep 04, 2026 at 11:45 AM',
    },
    aiReport: {
      iqa: {
        status: 'Good',
        score: 92,
        sharpness: 'Good focus',
        illumination: 'Standard',
        fieldOfView: 'Standard 45 degree',
      },
      drClassification: {
        grade: 'Moderate NPDR',
        confidence: 94.0,
        icdrScale: 2,
      },
      referableDR: {
        isReferable: true,
        confidence: 95.5,
        criteria: 'Moderate NPDR with perifoveal exudate cluster.',
      },
      microaneurysms: {
        detected: true,
        count: 14,
        quadrants: ['Superior-Temporal', 'Macular'],
        details: 'Microaneurysms clustered along the temporal arcade.',
      },
      hemorrhages: {
        detected: true,
        type: 'Dot-blot hemorrhages',
        quadrants: ['Temporal'],
        details: 'Dot hemorrhages in the parafoveal region.',
      },
      exudates: {
        detected: true,
        pattern: 'Hard exudates near fovea',
        macularInvolvement: true,
        details: 'Exudates threatening macular center; urgent OCT indicated.',
      },
      opticDisc: {
        status: 'Normal',
        cupToDiscRatio: 0.30,
        marginClarity: 'Clear',
        details: 'Normal appearance.',
      },
      vesselAnalysis: {
        status: 'Normal',
        arteriovenousNicking: false,
        tortuosity: 'Mild',
        caliberRatio: 'AV ratio 0.62',
        details: 'Moderate venular engorgement.',
      },
    },
  },
  {
    id: 'SESS-2026-0865',
    patientId: 'RX-104587',
    patientName: 'Robert Chen',
    patientAge: 43,
    patientGender: 'Male',
    patientArea: 'Metro Outreach Post',
    date: 'Sep 02, 2026',
    laterality: 'Left Eye (OS)',
    riskLevel: 'Low Risk',
    imageQuality: 'Good',
    drGrade: 'No DR',
    isReferable: false,
    reviewStatus: 'Reviewed',
    workerId: 'WRK-3082',
    workerName: 'Maya Chen',
    originalImageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    doctorAssessment: {
      doctorId: 'DOC-9041',
      doctorName: 'Dr. Alistair Vance, MD',
      decision: 'No immediate referral',
      notes: 'Clear bilateral fundus. Blood sugar well managed. Repeat screening in 1 year.',
      submittedAt: 'Sep 02, 2026 at 02:00 PM',
    },
    aiReport: {
      iqa: {
        status: 'Good',
        score: 97,
        sharpness: 'Sharp',
        illumination: 'Even',
        fieldOfView: 'Optimal',
      },
      drClassification: {
        grade: 'No DR',
        confidence: 99.1,
        icdrScale: 0,
      },
      referableDR: {
        isReferable: false,
        confidence: 99.5,
        criteria: 'Negative for DR.',
      },
      microaneurysms: {
        detected: false,
        count: 0,
        quadrants: [],
        details: 'None',
      },
      hemorrhages: {
        detected: false,
        type: 'None',
        quadrants: [],
        details: 'None',
      },
      exudates: {
        detected: false,
        pattern: 'None',
        macularInvolvement: false,
        details: 'None',
      },
      opticDisc: {
        status: 'Normal',
        cupToDiscRatio: 0.30,
        marginClarity: 'Clear',
        details: 'Normal physiologic disc.',
      },
      vesselAnalysis: {
        status: 'Normal',
        arteriovenousNicking: false,
        tortuosity: 'Normal',
        caliberRatio: 'AV ratio 0.66',
        details: 'Healthy vessels.',
      },
    },
  },
];

export const INITIAL_REFERRALS: ReferralRecord[] = [
  {
    id: 'REF-2026-0041',
    patientId: 'RX-104586',
    patientName: 'Amina Yusuf',
    sessionId: 'SESS-2026-0870',
    dateInitiated: 'Sep 04, 2026',
    urgency: 'Standard',
    currentStage: 'Hospital Visit',
    targetHospital: 'St. Jude Eye Institute — Retina OPD',
    specialty: 'Medical Retina / Macular Care',
    notes: 'CSME suspected. OCT scan scheduled. Patient transport arranged by Community Post.',
    history: [
      {
        stage: 'AI Screening',
        timestamp: 'Sep 04, 2026 at 09:30 AM',
        updatedBy: 'RetinaX AI Engine',
        notes: 'Identified Moderate NPDR with referable status (95.5% confidence)',
      },
      {
        stage: 'Doctor Review',
        timestamp: 'Sep 04, 2026 at 11:45 AM',
        updatedBy: 'Dr. Alistair Vance, MD',
        notes: 'Confirmed referable NPDR with CSME concern. Hospital referral issued.',
      },
      {
        stage: 'Referral Issued',
        timestamp: 'Sep 04, 2026 at 11:46 AM',
        updatedBy: 'System Automation',
        notes: 'Referral slip sent to East Valley PHC and patient emergency contact.',
      },
      {
        stage: 'Patient Informed',
        timestamp: 'Sep 05, 2026 at 10:15 AM',
        updatedBy: 'Maya Chen, CHW',
        notes: 'Called patient daughter; explained importance of clinic visit. Confirmed appointment.',
      },
      {
        stage: 'Hospital Visit',
        timestamp: 'Sep 07, 2026 at 09:00 AM',
        updatedBy: 'Clinic Intake Coordinator',
        notes: 'Patient checked in at Retina OPD. OCT scan completed.',
      },
    ],
  },
  {
    id: 'REF-2026-0042',
    patientId: 'RX-104582',
    patientName: 'Eleanor Vance',
    sessionId: 'SESS-2026-0891',
    dateInitiated: 'Today, 08:45 AM',
    urgency: 'Urgent',
    currentStage: 'Doctor Review',
    targetHospital: 'St. Jude Eye Institute Vitreoretinal Unit',
    specialty: 'Vitreoretinal Surgery & Anti-VEGF Clinic',
    notes: 'Severe NPDR with 4-quadrant hemorrhages and macular edema hazard.',
    history: [
      {
        stage: 'AI Screening',
        timestamp: 'Today, 08:30 AM',
        updatedBy: 'RetinaX AI Engine',
        notes: 'Flagged High Risk / Severe NPDR with high lesion density',
      },
      {
        stage: 'Doctor Review',
        timestamp: 'Today, 08:45 AM',
        updatedBy: 'System Auto-Triage',
        notes: 'Placed in Immediate Attention Queue for Dr. Alistair Vance',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-1',
    roleTarget: 'Doctor',
    title: 'Urgent: High-Risk Screening Awaiting Review',
    message: 'Patient Eleanor Vance (RX-104582) flagged with Severe NPDR and macular involvement.',
    timestamp: '15 minutes ago',
    isRead: false,
    type: 'high_risk',
    patientId: 'RX-104582',
    sessionId: 'SESS-2026-0891',
  },
  {
    id: 'NOTIF-2',
    roleTarget: 'Doctor',
    title: 'Referable DR Case Pending',
    message: 'Marcus Brody (RX-104583) has Moderate NPDR requiring confirmation.',
    timestamp: '2 hours ago',
    isRead: false,
    type: 'review_needed',
    patientId: 'RX-104583',
    sessionId: 'SESS-2026-0888',
  },
  {
    id: 'NOTIF-3',
    roleTarget: 'Doctor',
    title: 'Borderline Quality Image Needs Clinical Review',
    message: 'Sunita Patel (RX-104584) screening shows suspect disc cupping (0.55 cup/disc).',
    timestamp: '1 day ago',
    isRead: true,
    type: 'review_needed',
    patientId: 'RX-104584',
    sessionId: 'SESS-2026-0882',
  },
  {
    id: 'NOTIF-4',
    roleTarget: 'Healthcare Worker',
    title: 'Hospital Referral Issued for Amina Yusuf',
    message: 'Dr. Vance completed review for Amina Yusuf (RX-104586). Hospital referral to St. Jude Eye Institute issued.',
    timestamp: 'Yesterday',
    isRead: false,
    type: 'referral_update',
    patientId: 'RX-104586',
    sessionId: 'SESS-2026-0870',
  },
  {
    id: 'NOTIF-5',
    roleTarget: 'Healthcare Worker',
    title: 'Follow-up Needed for Sector 4',
    message: 'Reminder: 2 patients in East Valley PHC due for quarterly glucose & retinal follow-up.',
    timestamp: '2 days ago',
    isRead: true,
    type: 'followup',
  },
  {
    id: 'NOTIF-6',
    roleTarget: 'Patient',
    userId: 'RX-104582',
    title: 'Your Screening Session Is Being Reviewed',
    message: 'Your retinal images from today were received by Dr. Vance. You will receive an alert once assessment is signed.',
    timestamp: '20 minutes ago',
    isRead: false,
    type: 'review_needed',
    patientId: 'RX-104582',
    sessionId: 'SESS-2026-0891',
  },
  {
    id: 'NOTIF-7',
    roleTarget: 'Patient',
    userId: 'RX-104585',
    title: 'Annual Screening Report Available',
    message: 'Dr. Vance confirmed healthy retinal vessels with No Diabetic Retinopathy. Routine checkup due in 12 months.',
    timestamp: 'Sep 05, 2026',
    isRead: true,
    type: 'assessment_done',
    patientId: 'RX-104585',
    sessionId: 'SESS-2026-0879',
  },
];

export const initialDoctor = INITIAL_DOCTOR;
export const initialWorker = INITIAL_WORKER;
export const initialPatients = INITIAL_PATIENTS.map((p) => ({
  ...p,
  diabetesType: (p.id === 'RX-104582' ? 'Type 2' : p.id === 'RX-104583' ? 'Type 1' : 'Type 2') as 'Type 1' | 'Type 2',
  durationYears: p.id === 'RX-104582' ? 12 : p.id === 'RX-104583' ? 8 : 5,
  medications: p.id === 'RX-104582' ? 'Metformin 1000mg BID, Glimepiride 2mg' : 'Insulin Glargine 20u qhs, Lispro tid',
  notes: 'Regular checkup at PHC post. Fasting blood sugar 142 mg/dL.',
}));
export const initialScreenings = INITIAL_SESSIONS;

export const initialReferrals = [
  {
    id: 'REF-2026-0041',
    patientId: 'RX-104586',
    patientName: 'Amina Yusuf',
    doctorName: 'Dr. Alistair Vance, MD',
    doctorId: 'DOC-9041',
    dateIssued: 'Sep 04, 2026',
    targetAppointmentDate: 'Sep 18, 2026',
    hospitalName: 'St. Jude Eye Institute — Retina OPD',
    reason: 'CSME suspected. OCT scan scheduled. Patient transport arranged by Community Post.',
    urgency: 'Standard' as const,
    status: 'Visit Completed' as const,
    timeline: [
      { status: 'Referral Issued', date: 'Sep 04, 2026', note: 'Referral slip sent to East Valley PHC and patient emergency contact.' },
      { status: 'Appointment Booked', date: 'Sep 05, 2026', note: 'Called patient daughter; explained importance of clinic visit. Confirmed appointment.' },
      { status: 'Visit Completed', date: 'Sep 07, 2026', note: 'Patient checked in at Retina OPD. OCT scan completed.' },
    ],
  },
  {
    id: 'REF-2026-0042',
    patientId: 'RX-104582',
    patientName: 'Eleanor Vance',
    doctorName: 'Dr. Alistair Vance, MD',
    doctorId: 'DOC-9041',
    dateIssued: 'Today, 08:45 AM',
    targetAppointmentDate: 'Within 72 Hours',
    hospitalName: 'St. Jude Eye Institute Vitreoretinal Unit',
    reason: 'Severe NPDR with 4-quadrant hemorrhages and macular edema hazard.',
    urgency: 'Urgent' as const,
    status: 'Referral Issued' as const,
    timeline: [
      { status: 'Referral Issued', date: 'Today', note: 'Doctor referral issued by Dr. Alistair Vance.' },
    ],
  },
];

